import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4 bg-gray-100">
          <ul className="flex space-x-6">
            <li>
              <Link href="/" className="hover:underline font-medium">
                Axios
              </Link>
            </li>
            <li>
              <Link href="/marked" className="hover:underline font-medium">
                Marked
              </Link>
            </li>
          </ul>
        </nav>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
